import "server-only"

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"

import { mcpCreateFormToolInputSchema } from "@/lib/mcp-form-tool-schema"
import type { McpAuthContext } from "@/server/mcp/auth/mcp-auth-context"
import { mcpAuditService } from "@/server/mcp/audit/mcp-audit.service"
import {
  buildMcpErrorContent,
  McpToolError,
  type McpErrorCode,
} from "@/server/mcp/errors/mcp-errors"
import { mcpFormService } from "@/server/mcp/services/mcp-form.service"
import type { McpTool } from "@/server/mcp/tools/base-tool"

/**
 * create_form Tool
 *
 * Creates a form on an existing survey trackable from a structured JSON payload.
 * This tool only manages form definition. Sharing is handled separately by
 * the update_form_sharing tool.
 *
 * This tool behaves as a strict JSON contract:
 * - The payload is validated deterministically before any database write
 * - Validation errors include exact paths, received values, and expected types
 * - Agents can read validation errors, repair the payload, and retry
 * - Only supported field types (rating, checkboxes, notes, short_text) are accepted
 * - file_upload and youtube_video kinds are not supported via MCP
 *
 * The agent is responsible for constructing the form JSON externally.
 * No natural language interpretation occurs inside this tool.
 */
export class FormCreationTool implements McpTool {
  readonly name = "create_form" as const

  register(server: McpServer, authContext: McpAuthContext): void {
    server.registerTool(
      "create_form",
      {
        description:
          "Create a form on an existing survey trackable from a structured JSON payload. " +
          "The payload is validated strictly before creation. " +
          "On validation failure, structured errors with exact field paths are returned " +
          "so you can repair the payload and retry. " +
          "Each field must include key, kind, label, required, and config. " +
          "Rating config requires scale. " +
          "Checkboxes config requires options with label and value; checkbox option ids are generated by the server. " +
          "Notes and short_text configs support optional placeholder and maxLength. " +
          "Supported field kinds: rating, checkboxes, notes, short_text. " +
          "file_upload and youtube_video are not supported via MCP. " +
          "This tool does not manage public sharing; use update_form_sharing for that.",
        inputSchema: mcpCreateFormToolInputSchema,
      },
      async (args) => {
        const start = Date.now()
        try {
          if (!authContext.canUseTool("create_form")) {
            throw new McpToolError(
              "SCOPE_ERROR",
              "This token does not have permission to use create_form."
            )
          }

          // Delegate full validation and creation to the service.
          // The service runs strict Zod validation on the form payload before
          // any DB write, returning structured errors on failure.
          const result = await mcpFormService.createFormFromPayload(
            args.trackable_id,
            args.form,
            authContext
          )

          mcpAuditService.record({
            tokenId: authContext.tokenId,
            ownerUserId: authContext.ownerUserId,
            tool: "create_form",
            targetResourceId: args.trackable_id,
            success: result.success,
            errorCode: result.errorCode as McpErrorCode | undefined,
            durationMs: Date.now() - start,
            timestamp: new Date().toISOString(),
          })

          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify(result, null, 2),
              },
            ],
          }
        } catch (error) {
          mcpAuditService.record({
            tokenId: authContext.tokenId,
            ownerUserId: authContext.ownerUserId,
            tool: "create_form",
            targetResourceId: args.trackable_id,
            success: false,
            errorCode: (error as { code?: McpErrorCode }).code,
            durationMs: Date.now() - start,
            timestamp: new Date().toISOString(),
          })

          return {
            content: [
              { type: "text" as const, text: buildMcpErrorContent(error) },
            ],
          }
        }
      }
    )
  }
}
